# Pobierz oficjalny obraz Apache z PHP
FROM prestashop/prestashop:latest

# Skopiuj niestandardowy plik konfiguracyjny Apache
COPY apache2.conf /etc/apache2/apache2.conf

# Port, na którym działa PrestaShop (domyślnie 80)
EXPOSE 80