name: portainer
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.example.com`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls.certresolver=myresolver"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "app_data:/data"
    networks:
      - bridge-proxy

volumes:
  app_data:

networks:
  bridge-proxy:
    external: true