version: '3.8'

services:
  proxmox:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proxmox-ve
    networks:
      - bridge-proxy
    ports:
      - "8006:8006"  # Proxmox VE default port (dla celów testowych)
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.proxmox.rule=Host(`proxmox.example.com`)" # Zastąp `proxmox.example.com` swoją domeną
      - "traefik.http.routers.proxmox.entrypoints=websecure"
      - "traefik.http.routers.proxmox.tls=true"
      - "traefik.http.routers.proxmox.tls.certresolver=myresolver"
      - "traefik.http.services.proxmox.loadbalancer.server.port=8006"
    volumes:
      - proxmox_data:/var/lib/pve

networks:
  bridge-proxy:
    external: true

volumes:
  proxmox_data: