# Dockerfile for Traefik
FROM traefik:v2.4

# Copy Traefik configuration file (if needed)
#COPY traefik.yml /etc/traefik/traefik.yml
#COPY dynamic.yml /etc/traefik/dynamic.yml

# Expose necessary ports
EXPOSE 80
EXPOSE 443

# Entry point for Traefik
CMD ["traefik"]