# Pobierz obraz Traefik
FROM traefik:v2.5

# Możesz dodać dodatkowe komendy lub kopiować pliki konfiguracyjne, jeśli jest to konieczne
COPY traefik.yml /etc/traefik/traefik.yml

# Możesz również ustawić zmienne środowiskowe, jeśli jest to potrzebne
# ENV TZ=Europe/Warsaw

# Możesz dodać porty lub inne konfiguracje, jeśli to konieczne
# EXPOSE 80 443

# Nie musisz dodawać więcej, jeśli chcesz używać podstawowej konfiguracji Traefika