entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

certificatesResolvers:
  myresolver:
    acme:
      email: "youremail@example.com"
      storage: "/etc/traefik/acme.json"
      tlsChallenge: {}

api:
  dashboard:
    enabled: false